# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="robbyrussell"

# Extra plugins
plugins=(git common-aliases tmux sudo)

if [ -f $ZSH/oh-my-zsh.sh ]; then
    source $ZSH/oh-my-zsh.sh
else
    echo "Unable to find oh-my-zsh installation on $ZSH"
fi

export EDITOR='vim'
export GIT_EDITOR='vim'

# Aliases
alias ..='cd ..'
alias ll='ls -hl'
alias la='ls -a'
alias h='history'
alias df='df -h'
alias vi='vim'
alias v='vim'
alias tmux='TERM=xterm-256color \tmux'
alias rsync='rsync -azvP'
alias cat="/bin/cat --number"
alias ack="/usr/bin/ack-grep"
alias ducks='du -cksh * | sort -rn|head -11'

export OS=`uname`

if [ "$OS" = "Openbsd" ] ; then

    # working on -Current
    export CVSROOT=anoncvs@anoncvs.usa.openbsd.org:/cvs
    export PKG_PATH=http://ftp.spline.de/pub/OpenBSD/snapshots/packages/$(machine -a)/

    alias cvsup='cvs -q up -Pd'

    if [ -f /usr/local/bin/ggrep ]; then
        alias grep="ggrep --color=auto --exclude-dir=.git"
    fi

    if [ -f /usr/local/bin/colorls ]; then
        alias ls='colorls -G'
    fi
fi

if [ "$OS" = "Linux" ] ; then
    alias grep='grep --color=auto --exclude-dir=\.git'
fi

if [ "$OS" = "Darwin" ] ; then
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
fi

# Local bin folder
if [ -d ~/bin ]; then
    export PATH=~/bin:$PATH
fi

export PATH=/usr/local/bin:$PATH

# Load custom zsh files
for f in $(find ~/.zsh/ -name '*.zsh'); do source $f; done

# Load local zshrc if available
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

