# Executed by bash(1) for non-login shells.
#

# Global exports
if [ -f ~/.bash_exports ]; then
    . ~/.bash_exports
fi
 
# Alias definitions
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# Bash Functions
if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi

# Turn on advanced bash completion if the file exists 
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

PROMPT_COMMAND=prompt_func

# note: bind used instead of sticking these in .inputrc
bind "set completion-ignore-case on" 

# show list automatically, without double tab
bind "set show-all-if-ambiguous On" 

# no bell
bind "set bell-style none" 

# Add completion to source and .
complete -F _command source 
complete -F _command .

# append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

