# Starting a new shell (login and no-login) in Darwin, comprises:
#    profile
#    bash_profile

# Starting a new login shell under GNU/Linux:
#    bash_profile

# Starting a new interactive no-login shell under GNU/Linux:
#    bashrc

if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

